import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..')
const readSource = (path) => readFileSync(join(rootDir, path), 'utf8')

const apiSource = readSource('src/api/kafka.js')
const indexSource = readSource('src/api/index.js')
const routerSource = readSource('src/router/index.js')
const layoutSource = readSource('src/views/admin/AdminLayout.vue')
const pageSource = readSource('src/views/admin/KafkaManagement.vue')
const ragPageSource = readSource('src/views/admin/RAGEvaluationManagement.vue')

assert.match(apiSource, /url:\s*'\/kafka\/topics'/)
assert.match(apiSource, /url:\s*'\/kafka\/messages'/)
assert.match(apiSource, /url:\s*'\/kafka\/messages\/detail'/)
assert.match(indexSource, /export \* from '\.\/kafka'/)

assert.match(routerSource, /path:\s*'kafka'/)
assert.match(routerSource, /KafkaManagement\.vue/)
assert.match(layoutSource, /index="\/admin\/kafka"/)
assert.match(layoutSource, /Kafka 可视化/)

assert.match(pageSource, /Kafka 可视化/)
assert.match(pageSource, /getKafkaTopics/)
assert.match(pageSource, /getKafkaMessages/)
assert.match(pageSource, /getKafkaMessageDetail/)
assert.match(pageSource, /CustomPagination/)
assert.match(pageSource, /topicCards/)
assert.match(pageSource, /filterForm/)
assert.match(pageSource, /currentPage/)
assert.match(pageSource, /pageSize/)
assert.match(pageSource, /page:\s*currentPage\.value/)
assert.match(pageSource, /page_size:\s*pageSize\.value/)
assert.match(pageSource, /session_id/)
assert.match(pageSource, /user_id/)
assert.match(pageSource, /question_id/)
assert.match(pageSource, /document_uuid/)
assert.match(pageSource, /expert_key/)
assert.match(pageSource, /isExpertTopic/)
assert.match(pageSource, /v-if="isExpertTopic"\s+label="专家"/)
assert.match(pageSource, /expert_name\s*\|\|\s*row\.expert_key/)
assert.match(pageSource, /active_partition_count/)
assert.match(pageSource, /empty_partition_count/)
assert.match(pageSource, /partition-list/)
assert.match(pageSource, /grid-auto-flow:\s*column/)
assert.match(pageSource, /min-height:\s*96px/)
assert.match(pageSource, /overflow:\s*auto/)
assert.match(pageSource, /sessionStorage\.setItem\(stateStorageKey/)
assert.match(pageSource, /sessionStorage\.getItem\(stateStorageKey/)
assert.match(pageSource, /topicScrollLeft/)
assert.match(pageSource, /scrollLeft\s*=\s*Number\(state\.topicScrollLeft/)
assert.match(pageSource, /action-buttons/)
assert.match(pageSource, /class-name="operation-column"/)
assert.match(pageSource, /查看评估/)
assert.match(pageSource, /path:\s*'\/admin\/evaluations'/)
assert.match(pageSource, /related_evaluation/)
assert.match(pageSource, /消息详情/)
assert.match(pageSource, /消息内容/)
assert.match(pageSource, /if \(filterForm\.value\.topic\) {\s*fetchMessages\(\)\s*}/)
assert.doesNotMatch(pageSource, /console\./)

assert.match(ragPageSource, /useRoute/)
assert.match(ragPageSource, /evaluation_id:\s*route\.query\.evaluation_id/)
assert.match(ragPageSource, /route\.query\.evaluation_id/)
assert.doesNotMatch(ragPageSource, /console\./)

console.log('kafka management wiring verified')
